<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTTn4xA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTTn4xA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTTn4xA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTTn4xA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXTTn4xA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XTTn4xA',
    'container.build_id' => '2399d3a4',
    'container.build_time' => 1617027527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTTn4xA');
