<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIT9JswY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIT9JswY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIT9JswY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIT9JswY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIT9JswY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IT9JswY',
    'container.build_id' => '39a4dd3d',
    'container.build_time' => 1615773240,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIT9JswY');
